
experiment:
    type: lrm
    seed: 42
    parent: test
    child: training-fov-random_per_object

model:
    camera_embed_dim: 1024
    rendering_samples_per_ray: 96
    transformer_dim: 512
    transformer_layers: 12
    transformer_heads: 8
    triplane_low_res: 32
    triplane_high_res: 64
    triplane_dim: 32
    encoder_type: dinov2
    encoder_model_name: dinov2_vits14_reg
    encoder_feat_dim: 384
    encoder_freeze: false

dataset:
    subsets:
        -   name: objaverse
            root_dirs:
                - /home/renderings-modelry-chairs-randomfov/100Chairs_random_per_GLB
            meta_path:
                train: /home/renderings-modelry-chairs-randomfov/train.json
                val: /home/renderings-modelry-chairs-randomfov/val.json
            sample_rate: 1.0
    sample_side_views: 3
    source_image_res: 224
    render_image:
        low: 64
        high: 192
        region: 64
    normalize_camera: true
    normed_dist_to_center: auto
    num_train_workers: 5
    num_val_workers: 5
    pin_mem: true

train:
    mixed_precision: bf16
    find_unused_parameters: false
    loss:
        pixel_weight: 1.0
        perceptual_weight: 1.0
        tv_weight: 5e-4
    optim:
        lr: 4e-4
        weight_decay: 0.05
        beta1: 0.9
        beta2: 0.95
        clip_grad_norm: 1.0
    scheduler:
        type: cosine
        warmup_real_iters: 3000
    batch_size: 10
    accum_steps: 1
    epochs: 30000
    debug_global_steps: null

val:
    batch_size: 10
    global_step_period: 50
    debug_batches: null

saver:
    auto_resume: true
    load_model: null
    checkpoint_root: ./exps/checkpoints
    checkpoint_global_steps: 50
    checkpoint_keep_level: 5

logger:
    stream_level: WARNING
    log_level: INFO
    log_root: ./exps/logs
    tracker_root: ./exps/trackers
    enable_profiler: false
    trackers:
        - wandb
    image_monitor:
        train_global_steps: 50
        samples_per_log: 4

compile:
    suppress_errors: true
    print_specializations: true
    disable: true
